### ISSUE TITLE
No error message for wrong class

### ISSUE THREAD

**Issue by catap** [xdotai/play-json-extensions#26]
Hi,

When I try make something likes it:

``` scala
class Version(version_id: Int = Int.MinValue, completed: Boolean)

object Version {

  implicit val versionFormat = Jsonx.formatCaseClassUseDefaults[Version]

}
```

I have error message that can help understand what happens:

```
[error]   implicit val versionFormat = Jsonx.formatCaseClassUseDefaults[Version]
[error]                                                                ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

I think it is better then an error message said that formatCaseClassUseDefaults expect only case class ;)

**Comment by cvogt** [comment]
I interpret this as: better error message desired when trying the macro on a class which is not a case class

**Comment by cvogt** [comment]
seems to be working now
```

**Comment by cvogt** [comment]
tried in 0.9.0

**Comment by catap** [comment]
Yay! Thanks man! I haven't remember where I used it, but... thanks!
