### ISSUE TITLE
Is version 0.14.0 legitimate?

### ISSUE THREAD

**Issue by NthPortal** [xdotai/play-json-extensions#60]
On Maven Central, there is a [version 0.14.0](https://repo1.maven.org/maven2/ai/x/play-json-extensions_2.12/) published for this project; however, this GitHub repo does not contain a release, tag, or branch for 0.14.0, and the `build.sbt` on `master` has the version 0.10.0. Is the version on Maven Central legitimate?

**Comment by jtjeferreira** [comment]
https://github.com/rtimush/sbt-updates is also reporting that the latest version is 0.14.0 which might confuse some users...
