### ISSUE TITLE
Release for 2.13.0 wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [xdotai/play-json-extensions#67]
subj

**Comment by caente** [comment]
version 0.40.0 supports 2.13 now
cc/ @xuwei-k

**Comment by plokhotnyuk** [comment]
is it on a way to the maven cenral?
http://repo1.maven.org/maven2/ai/x/play-json-extensions_2.13/

**Comment by caente** [comment]
I accidentally only released it for 2.12
I re-released it now 2.11, 2.12 and 2.13
the new version is 0.40.1

**Comment by caente** [comment]
so it is released... but still don't see it anywhere o_O
hopefully it's just a matter of time

**Comment by caente** [comment]
alright, it is here, at least https://oss.sonatype.org/content/groups/public/ai/x/

**Comment by caente** [comment]
I can confirm that it's in the release repo of sonatype

**Comment by plokhotnyuk** [comment]
@caente thanks! 
[already trying it](https://github.com/plokhotnyuk/jsoniter-scala/commit/53d1b84843187679762eb2d5baebc847c8ea81ed)

**Comment by xuwei-k** [comment]
missing tag on GitHub?

https://github.com/xdotai/play-json-extensions/tags

![スクリーンショット 2019-06-14 14 58 38](https://user-images.githubusercontent.com/389787/59486632-e93f2d80-8eb4-11e9-9757-f3fc4d2bede1.png)

**Comment by caente** [comment]
indeed!
