### ISSUE TITLE
Is version 0.41.0 for Scala 2.12.x published

### ISSUE THREAD

**Issue by gwak** [xdotai/play-json-extensions#79]
Hello,

On the README it's advertised that the current version available for Play 2.8 is version 0.41.0:
```scala
libraryDependencies += "ai.x" %% "play-json-extensions" % "0.41.0"
```

But the dependency can't be found by sbt, so is it released yet ?

Thanks

**Comment by caente** [comment]
README updated and pending PRs merged, the new version is 0.42.0
cc/ @dhoepelman  @mtsokol  @Rogach @xuwei-k
